#!/bin/bash

# Define the session name
SESSION_NAME="vps_session"

# Start a new tmux session with the first command
tmux new-session -d -s $SESSION_NAME -n "Chromium"
tmux send-keys "chromium --proxy-server='socks5://localhost:9000'" C-m

# Split the window and run the second command
tmux split-window -t $SESSION_NAME
tmux send-keys "ssh -D9000 -N hetznera" C-m

# Attach to the tmux session
tmux attach-session -t $SESSION_NAME

